image: cryptexlabs/docker-jq:1.0.0

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  only:
    refs:
      - master
      - tags
  script:
    - sh ./app/dns-server/bin/build-deploy.sh