apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: minikube-ingress-dns
    context: .
    sync:
      manual:
      # Sync all the javascript files that are in the src folder
      # with the container src folder
      - src: 'nodejs/src/**/*.js'
        dest: .
    docker:
      dockerfile: 'docker/nodejs/Dockerfile'