apiVersion: v1
kind: Service
metadata:
  name: kube-ingress-dns-minikube
  namespace: kube-system
spec:
  selector:
    app: minikube-ingress-dns
  clusterIP: None
  ports:
    - name: tcp-port
      port: 5353
      targetPort: 5353
      protocol: TCP
    - name: udp-port
      port: 5353
      targetPort: 5353
      protocol: UDP