apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-dns
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: minikube-dns
  template:
    metadata:
      labels:
        app: minikube-dns
    spec:
      containers:
        - name: minikube-dns
          image: cryptexlabs/minikube-dns:latest
          ports:
            - containerPort: 53
          env:
            - name: MINIKUBE_IP
              value: {{ .Values.minikubeIP }}